In [ ]:
# Standard library imports
import json

# Local application imports
from src.backtester import Backtester
from src.utils import load_data

config = json.load(open("./config.json"))
asset_returns, features, rebalance_dates = load_data(config)

backtester = Backtester(
                        asset_returns=asset_returns,
                        config=config,
                        rebalance_dates=rebalance_dates,
                        features=features)

backtests = backtester.run_backtests()

In [100]:
import pandas as pd
asset_prices = pd.read_csv(config['assets_path'], index_col=0)
asset_prices.index = pd.to_datetime(asset_prices.index)

In [106]:
def backtest_portfolios(self, historical_portfolios):
        '''
        Given a historical portfolio and the total returns, computes the performance backtest.
        '''
        print('running backtest performance')
        backtests = {}
        for model in self.generators:
            print(f"    {model.name}")
            backtests[model.name] = {}
            portfolios = historical_portfolios[model.name]
            backtest = portfolios.reindex(asset_prices.index)
            backtest = backtest.fillna(method='ffill').dropna()
            returns = asset_prices.pct_change()
            returns = returns.reindex(backtest.index)
            backtest *= returns
            backtest /= 100
            backtest = backtest.sum(axis=1)
            backtest.iloc[0] = 0
            backtest += 1
            backtest = backtest.cumprod()
            backtest *= 100
            backtests[model.name]['total_return_serie'] = backtest
            backtests[model.name]['portfolios'] = portfolios
        return backtests

In [107]:
bt = {}
bt['historical'] =  backtests['historical']['portfolios']
bt['CTGAN'] =  backtests['CTGAN']['portfolios']
backtest_portfolios(backtester, bt)
True

running backtest performance
    historical
date
2008-12-31    1.000000
2009-01-01    1.000660
2009-01-02    0.996233
2009-01-03    0.996233
2009-01-04    0.996233
                ...
2022-04-29    5.376046
2022-04-30    5.376046
2022-05-01    5.376046
2022-05-02    5.468492
2022-05-03    5.466309
Length: 4872, dtype: float64
    CTGAN
date
2008-12-31    1.000000
2009-01-01    1.000653
2009-01-02    1.011853
2009-01-03    1.011853
2009-01-04    1.011853
                ...
2022-04-29    5.948770
2022-04-30    5.948770
2022-05-01    5.948770
2022-05-02    6.051065
2022-05-03    6.048649
Length: 4872, dtype: float64

True

In [49]:
backtester.asset

,us_equities,us_equities_tech,global_equities,em_equities,us_hy,us_ig,em_debt,cmdty,long_term_treasuries,short_term_treasuries
date,,,,,,,,,,
2002-12-31,0.286652,0.494293,0.338222,0.558269,0.195806,0.072806,0.222126,0.239316,0.024833,0.019171
2003-01-01,0.286652,0.494293,0.338222,0.558964,0.195806,0.072806,0.222126,0.239316,0.024833,0.019171
2003-01-02,0.241424,0.426823,0.308806,0.575397,0.194850,0.075620,0.223109,0.208227,0.034641,0.020381
2003-01-03,0.242025,0.421609,0.304685,0.544260,0.195740,0.073870,0.220233,0.191051,0.033989,0.020596
2003-01-04,0.242025,0.421609,0.304685,0.544260,0.195740,0.073870,0.220233,0.191051,0.033989,0.020596
...,...,...,...,...,...,...,...,...,...,...
2021-04-29,-0.005163,-0.073396,-0.038677,-0.191046,-0.056008,-0.117188,-0.143587,0.438434,-0.120085,-0.035449
2021-04-30,0.001966,-0.066146,-0.030790,-0.180943,-0.056114,-0.117495,-0.145051,0.435340,-0.122253,-0.035449
2021-05-01,0.001966,-0.066146,-0.030790,-0.180943,-0.056114,-0.117495,-0.145051,0.435340,-0.122253,-0.035449
2021-05-02,0.007658,-0.050088,-0.030316,-0.183659,-0.061884,-0.126496,-0.149304,0.429774,-0.135736,-0.035844
2021-05-03,0.006678,-0.046278,-0.033598,-0.178396,-0.062978,-0.128063,-0.148523,0.433440,-0.136207,-0.035982